### ISSUE TITLE
Please publish to 'https://maven.pkg.jetbrains.space/public/'

### ISSUE THREAD

**Issue by ber4444** [Kotlin/kotlinx.collections.immutable#105]
we need `org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.3.3` published to the JetBrains space since `jcenter()` is going away

**Comment by JakeWharton** [comment]
Resolved by #96 already? Specifically, https://github.com/Kotlin/kotlinx.collections.immutable/issues/96#issuecomment-813117739.

**Comment by ber4444** [comment]
Thanks, overriding the dependency version to 0.3.4 works with Compose.
