### ISSUE TITLE
Do ya really need unordered collections?

### ISSUE THREAD

**Issue by swankjesse** [Kotlin/kotlinx.collections.immutable#11]
Presumably the only reason to choose unordered is a small performance improvement.

I make two claims:

1. The programmer + code reviewer cost of making a decision on each use far outweighs the benefit of that decision. You’re forced to make a choice 100% of the time but the decision is relevant 1% of the time.

2. In situations where the cost of retaining order is significant, it’s likely that another collection altogether is a better match. Rather than optimizing from `ImmutableSet<Date>` to `ImmutableHashSet<Date>`, programmers should probably skip right to `Array<Long>`.

Thanks for your consideration.

**Comment by ilya-g** [comment]
If you don't care about the performance benefit, just use the implementation provided by default, for example coming from the functions `immutableSetOf`/ `toImmutableSet`.

> In situations where the cost of retaining order is significant, it’s likely that another collection altogether is a better match

Exactly. That's why we provide unordered collections as well – because they can be a better match in this situation.
