### ISSUE TITLE
Support for M1 simulators

### ISSUE THREAD

**Issue by karelp** [Kotlin/kotlinx.collections.immutable#118]
Since Kotlin 1.5.30 there are [M1 simulator targets available](https://kotlinlang.org/docs/whatsnew1530.html#apple-silicon-support). Would be great if you could add support for these as any project using this library cannot use the simulator targets until then. Hopefully it’s as simple as adding the new targets to build.gradle.kts.

**Comment by ilya-g** [comment]
Should be fixed by PR #121 (https://github.com/Kotlin/kotlinx.collections.immutable/pull/121/files#diff-a6fced4b4e4a99784a2b92028b1adbc8c0ca28ff54e264b0e73727b3d4a460cfR21).

**Comment by qurbonzoda** [comment]
Released with 0.3.5 version of the library. Thank you for the feedback!
