### ISSUE TITLE
Documentation issue ?

### ISSUE THREAD

**Issue by vgodara** [Kotlin/kotlinx.collections.immutable#122]
Hey guys please take a look at the following example 

val mainList = listOf(1,1,2,3)
val subList = listOf(1)
val element = 1
// The following use of minus function produces diffrent results

// If we use minus function and pass a list it will remove all entries of 1  
mainList.minus(subList)

// However if we use minus function and pass an element it will remove the first entry of the element which is what is written in documents. But it's not clarified in documents what happens if we use minus function with a list as an argument.

https://pl.kotl.in/aIx0nMu2y

**Comment by ilya-g** [comment]
This aspect of behavior is explained in this page about `plus` and `minus` operators for Collections: https://kotlinlang.org/docs/collection-plus-minus.html
There's also API reference documentation for each overload of `minus`: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/minus.html
