### ISSUE TITLE
Your license is missing your signature

### ISSUE THREAD

**Issue by joserobjr** [Kotlin/kotlinx.collections.immutable#13]
You need to sign it at [line 289](https://github.com/Kotlin/kotlinx.collections.immutable/blob/7b777462c2002f37bd340ea00e20979ab2efd8d4/LICENSE#L189)

`Copyright {yyyy} {name of copyright owner}`

**Comment by ilya-g** [comment]
Thanks for spotting this, I've fixed the license.
