### ISSUE TITLE
Add support for linuxArm64

### ISSUE THREAD

**Issue by Nailik** [Kotlin/kotlinx.collections.immutable#145]
There is no support for `linuxArm64Main` or `linuxArm64Test`.
This blocks a lot of ppl from using this in their multiplatform projects/libraries without adding compose dependencies.

Therefore the libraries cannot make stable data classes for compose which would be very important.

This is related to https://github.com/Kotlin/kotlinx.collections.immutable/issues/79

**Comment by Nailik** [comment]
bump

**Comment by qurbonzoda** [comment]
Hi!
The newly released version 0.3.6 supports all targets supported by the K/N compiler, including linuxArm64.
Please try it and provide us with feedback.
