### ISSUE TITLE
Dead Repo

### ISSUE THREAD

**Issue by shaqaruden** [Kotlin/kotlinx.collections.immutable#149]
No updates in over a year. Should I just give up on using this package?

**Comment by LaylaMeower** [comment]
The kotlin compiler is currently under a rewrite; My guess - repositories like Kotlin Scripting and Immutable Collections will be updated _after_ K2 is complete. That's not official tho, just my theory. It could be they're cancelled.

**Comment by qwwdfsad** [comment]
We do provide basic maintenance (e.g. releasing new targets/Kotlin versions), but nothing beyond that.

`kotlinx.collections.immutable` are quite good as they are right now, with battle-tested and well-covered API and implementation to the extent they are used within Compose and internally.

Neither creative activity just for the sake of it nor stabilizing it is currently on our radar
