### ISSUE TITLE
Update kotlin version to 1.9.20

### ISSUE THREAD

**Issue by igoriakovlev** [Kotlin/kotlinx.collections.immutable#151]
Hi,

Could you please update kotlin version up to 1.9.20 (Beta?).
K/Wasm need it to add new wasm targets into the library.

Thanks

**Comment by qurbonzoda** [comment]
Hi,
The library now uses Kotlin 1.9.0 in master. The Kotlin version can be upgraded to 1.9.20 together with the addition of new WASM targets. No additional changes should be needed to bump Kotlin version.

**Comment by igoriakovlev** [comment]
Thank you a lot!

**Comment by Goooler** [comment]
This could be closed due to #156.
