### ISSUE TITLE
Implementation methods inherited from `kotlin-stdlib` `Abstract[x]` are not visible in interfaces 

### ISSUE THREAD

**Issue by Lordfirespeed** [Kotlin/kotlinx.collections.immutable#152]
For example, `PersistentList`. The interface declaration:
```kt
public interface ImmutableList<out E> : List<E>, ImmutableCollection<E> { /* ... */ }
public interface PersistentList<out E> : ImmutableList<E>, PersistentCollection<E> { /* ... */ }
```
reasonably claims it implements the `List` interface.

The base implementation declaration:
```kt
abstract class AbstractPersistentList<E> : PersistentList<E>, AbstractList<E>() { /* ... */ }
```

inherits `stdlib`'s `AbstractList`, which contains methods not present in the `List` interface, such as 
- `fun equals(other: Any?): Boolean`
- `fun hashCode(): Int`

Which means that following the declaration of a `PersistentList`'s `hashCode` function, for example, will go to `Any#hashCode`, 
which is misleading.
```kt
val myPersistentList: PersistentList<T> = persistentListOf(1,2,3)
myPersistentList.hashCode() // go to declaration -> `Any#hashCode`. Should be `AbstractList#hashCode`
```

**Comment by Lordfirespeed** [comment]
Truthfully, the same issue is apparent with `stdlib` builtins such as `listOf`, so perhaps this is more of a them problem. :joy:

**Comment by qurbonzoda** [comment]
Hi,
Because `PersistentList` is an interface and does not provide `hashCode` implementation, navigating to the function leads to the `Any.hashCode()`. This is an expected behavior of the IntelliJ IDEA.
