### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by mipastgt** [Kotlin/kotlinx.collections.immutable#158]
Are you planning to support the new WASM target in the near future? I am just evaluating the feasibility of converting my current project to a WASM browser project.

**Comment by colinrtwhite** [comment]
+1 as this blocks [Coil](https://github.com/coil-kt/coil) from supporting Wasm. Looks like wasm support is already implemented [here](https://github.com/Kotlin/kotlinx.collections.immutable/pull/156).

**Comment by nowiwr01w** [comment]
+1 because we need Coil for Web 🥲🥲🥲

**Comment by qurbonzoda** [comment]
Hi,
Wasm targets are now supported in the latest release - 0.3.7.
Please try and share your feedback.

**Comment by mipastgt** [comment]
Great, thank you. Maybe you should also add that to the Readme file.
