### ISSUE TITLE
Why not published on jcenter?

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.collections.immutable#16]
Hi,
Why isn't this library published on jcenter?
Doing so would allow the [methods count to appear here](http://www.methodscount.com/?lib=org.jetbrains.kotlinx%3Akotlinx-collections-immutable%3A0.1) which can be important for Android apps nearing the dex size limit

**Comment by ilya-g** [comment]
methodscount.com is not longer that it is used to be, but including this package to jcenter may still worth it for other reasons.

So now it should be available in jcenter too: https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-collections-immutable/
