### ISSUE TITLE
Explicit API mode?

### ISSUE THREAD

**Issue by Goooler** [Kotlin/kotlinx.collections.immutable#167]
I see some APIs under `core/commonMain/src` with the explicit modifiers and types but some of them are not, should we enable it by adding `-Xexplicit-api=strict` and check types strictly?

See https://github.com/Kotlin/KEEP/blob/master/proposals/explicit-api-mode.md

**Comment by Goooler** [comment]
Probably we can add [Binary compatibility validator](https://github.com/Kotlin/binary-compatibility-validator) first.

**Comment by qurbonzoda** [comment]
Adding the both checks is quite important and will bring the library a step closer to the stable release.
Could you please create a separate issue for adding binary compatibility validator?

**Comment by Goooler** [comment]
I'll add the validator tonight, so we don't need it explicitly.

**Comment by qurbonzoda** [comment]
An issue still has some benefits. 
* It will be a place to discuss and track the changes proposed in the associated pull request. 
* It can provide additional context, such as the rationale behind the changes, the problem being addressed, and any relevant information. This documentation becomes valuable for future reference and for understanding the context of the changes.
* It helps in separating the process of identifying and discussing a problem or feature (issue) from the process of implementing the solution (pull request).
* It can be referenced in release notes.

**Comment by Goooler** [comment]
It's in #168.
