### ISSUE TITLE
Make Collections Serializable

### ISSUE THREAD

**Issue by Fleshgrinder** [Kotlin/kotlinx.collections.immutable#17]
The other collection types are serializable as well, there is imho no reason why the immutable versions should not be.

**Comment by yuriykulikov** [comment]
Is that really required? Java serialization is not really that useful. It will also be dropped by Oracle at some point.

**Comment by yuriykulikov** [comment]
> Is that really required? Java serialization is not really that useful. It will also be dropped by Oracle at some point.

Here is a clarification. According to Mark Reinhold (chief architect at Oracle): "[Serialization] was a horrible mistake in 1997," he said. "Some of us tried to fight it, but it went in, and there it is. ...We like to call serialization 'the gift that keeps on giving,' and the type of gift it keeps on giving is security vulnerabilities.... Probably a third of all Java vulnerabilities have involved serialization; it could be over half. It is an astonishingly fecund source of vulnerabilities, not to mention instabilities."

Sure, this is a long term goal, but it is clear that Java Serialization was not a good idea in the first place. While it makes sense to support this for compatiliblty reasons,  I do not think that it is worth adding to a brand-new implementation.

Nowdays there are much better ways to achieve the same goal.

**Comment by qurbonzoda** [comment]
Later we could make the immutable collections serializable by [Kotlin Serialization](https://github.com/Kotlin/kotlinx.serialization).

**Comment by Fleshgrinder** [comment]
Closing this as I have no use case anymore for it. 😊

**Comment by pwgraham91** [comment]
This would be useful to me to be able to pass PersistentLists inside java.io.Serializable classes between destinations in android navigation: https://developer.android.com/guide/navigation/navigation-pass-data#supported_argument_types
