### ISSUE TITLE
Is the Android fast iteratable methods supported?

### ISSUE THREAD

**Issue by mortenholmgaard** [Kotlin/kotlinx.collections.immutable#173]
Does **kotlinx.collections.immutable** support the fast iterations methods?
[See Android documentation for them here.](https://developer.android.com/reference/kotlin/androidx/compose/ui/util/package-summary#(kotlin.collections.List).fastForEach(kotlin.Function1))

**Comment by JakeWharton** [comment]
Those (poorly-named) functions are only for use with ArrayList as it supports fast random access. For List implementations that are not backed by simple arrays, those functions will almost always be slower than the regular functions.
