### ISSUE TITLE
Exception removing keys from a ImmutableMap

### ISSUE THREAD

**Issue by cout970** [Kotlin/kotlinx.collections.immutable#18]
Description: An unexpected exception occurred when I tried to remove values form the a ImmutableMap, after a bit of testing I found that the error had nothing to do with my code, the following example show the minimal code required to cause the crash.

Code:
```kotlin
import kotlinx.collections.immutable.*

fun main(args: Array<String>) {
    val map = immutableMapOf(
            0 to "a",
            1 to "b",
            2 to "c"
    )

    val newMap = map - setOf(2)

    println(newMap)
}
```

Expected result: `{0=a, 1=b}`
Actual result:
```
Exception in thread "main" java.lang.IllegalStateException: Required value was null.
```
Rest of the stacktrace: https://pastebin.com/UCVMiZmC
Version used: 0.1

**Comment by ilya-g** [comment]
Thanks for the failing example, I've tracked down the bug and fixed it in the `develop` branch.
