### ISSUE TITLE
Version 0.2 was removed from BT KotlinX repository

### ISSUE THREAD

**Issue by Taym** [Kotlin/kotlinx.collections.immutable#191]
Hi! 

There is a project that uses the old version 0.2 of the library but it seems this version was removed from 
```
https://dl.bintray.com/kotlin/kotlinx/
```

The project is including this library as follows:
```
dependencies {
    compile("org.jetbrains.kotlinx:kotlinx-collections-immutable:0.2")
}

repositories {
    maven("https://dl.bintray.com/kotlin/kotlinx")
}
```
But Gradle is not able to find this dependency, so I checked in [Maven Central](https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-collections-immutable/0.2)  and I am also not able to download the Jar file, which means the artifact was removed I believe.

Could you please re-upload the artifact for version 0.2?

**Comment by Goooler** [comment]
Bintray is down.

Try out `maven("https://maven.aliyun.com/repository/public")` as a workaround.

**Comment by ilya-g** [comment]
You can use the following repository with the archived versions of kotlinx libraries that were published only to bintray:
https://maven.pkg.jetbrains.space/kotlin/p/kotlinx/archive
it has kotlinx.collections.immutable library versions 0.1 and 0.2

But we don't give any guarantees about its availability, so please plan the migration to 0.3.x versions which are published to maven central.

**Comment by Taym** [comment]
Thanks a lot! both repositories worked.
