### ISSUE TITLE
Improve performance scaling

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [Kotlin/kotlinx.collections.immutable#2]
The choice of internal representation for some PCollections scales on O(log2 n), where other implementations like Clojure's scale on O(log32 n)*

PCollections is a friendly implementation of persistent collections that's available today with little friction, but other options could be considered.

*Sources: 

The Joy Of Clojure 2nd Ed Section 5.1.3  

> When learning about Clojure’s persistent data structures, you’re likely to hear the term O(log32 n) for those based on the persistent hash trie and O(log2 n) for the sorted structures. Accessing an element in a Clojure persistent structure by index is O(log n), or logarithmic. 

https://github.com/GlenKPeterson/UncleJim/wiki/UncleJim%20vs.%20PCollections

**Comment by FranciscoE-Hudl** [comment]
It's a nitpick given that you're asking for feedback on Twitter.

**Comment by andrewoma** [comment]
My dexx collections are a port of Scala's collections having the O(log32 n)* performance characteristics if you're interested: https://github.com/andrewoma/dexx

**Comment by jjl** [comment]
I found [paguro](https://github.com/GlenKPeterson/Paguro) (formerly UncleJim), which are based on clojure's collections but made typesafe.

Clojure's collections are arguably the best on the JVM, bar the way everything gets turned into object and Paguro seems to be well-built.

**Comment by ilya-g** [comment]
In 0.2 collections use trie structures with scaling factor of 32, see the changelog https://github.com/Kotlin/kotlinx.collections.immutable/releases/tag/v0.2
