### ISSUE TITLE
Support MPP

### ISSUE THREAD

**Issue by jcornaz** [Kotlin/kotlinx.collections.immutable#21]
It would be great if this library could be used in common and javascript modules of multi-platform projects.

**Comment by ilya-g** [comment]
That's definitely in our plans, though we want to start with JVM library first.

**Comment by adam-arold** [comment]
I don't understand why an official Kotlin library is not multiplatform **by default**. It is just a missed opportunity since you need nothing from Java to implement this.

**Comment by adam-arold** [comment]
I just checked the latest version (`0.2`) and I see no external dependencies. what is blocking transforming this to MPP?

**Comment by JakeWharton** [comment]
Time. Effort. The usual things...

See above. It's coming.

**Comment by qurbonzoda** [comment]
Implemented end included in `v0.3`. Thank you all!

**Comment by adam-arold** [comment]
**This is great!!** Thanks a lot for getting around this so quickly!

**Comment by qurbonzoda** [comment]
We look forward to your feedback and suggestions

**Comment by adam-arold** [comment]
I'll share it if something comes up!
