### ISSUE TITLE
Investigate benefits of implementing addAll operation in persistent list and its builder

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/kotlinx.collections.immutable#31]
Currently it delegates to `addAll` of the builder, which is inherited from the AbstractMutableCollections and adds elements one by one.

**Comment by ilya-g** [comment]
Currently it delegates to `addAll` of the builder, which is inherited from the AbstractMutableCollections and adds elements one by one.

**Comment by qurbonzoda** [comment]
Implemented here: https://github.com/Kotlin/kotlinx.collections.immutable/pull/50

**Comment by qurbonzoda** [comment]
Included in `v0.3`
