### ISSUE TITLE
AbstractMethodError: getEntries()Ljava/util/Set; of abstract class kotlin.collections.AbstractMap

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.collections.immutable#49]
I got an error, maybe a compiler's one.

I am using Kotlin `1.3.41` and immutable `0.2`, here the reproducer:

```kotlin
import kotlinx.collections.immutable.ImmutableCollection
import kotlinx.collections.immutable.ImmutableMap
import kotlinx.collections.immutable.ImmutableSet
import kotlinx.collections.immutable.persistentSetOf

fun main() {
    MyMap<Unit,Unit>().entries
}

class MyMap<K,V>: AbstractMap<K,V>(),ImmutableMap<K,V>{
    override val entries: ImmutableSet<Map.Entry<K, V>>
        get() = persistentSetOf()
    override val keys: ImmutableSet<K>
        get() = persistentSetOf()
    override val values: ImmutableCollection<V>
        get() = persistentSetOf()
}
```

```
Exception in thread "main" java.lang.AbstractMethodError: Receiver class MyMap does not define or inherit an implementation of the resolved method abstract getEntries()Ljava/util/Set; of abstract class kotlin.collections.AbstractMap.
	at kotlin.collections.AbstractMap.entrySet(AbstractMap.kt:21)
	at TestKt.main(Test.kt:7)
	at TestKt.main(Test.kt)
```

**Comment by qurbonzoda** [comment]
This is a known compiler bug.
As a workaround you can declare an internal `getEntries()` method that is marked as @PublishedApi, see:
https://github.com/Kotlin/kotlinx.collections.immutable/blob/2d7b75a2fd37007214657302c074a400635cbd94/kotlinx-collections-immutable/src/main/kotlin/kotlinx/collections/immutable/implementations/immutableMap/PersistentHashMap.kt#L45

**Comment by zhelenskiy** [comment]
Apply the following patch to workaround the issue.
[Fix_compiler_bug.patch](https://github.com/Kotlin/kotlinx.collections.immutable/files/13326860/Fix_compiler_bug.patch)

**Comment by zhelenskiy** [comment]
Is the bug reported at YouTrack?
