### ISSUE TITLE
Dexx may provide alternative implementations to PCollections

### ISSUE THREAD

**Issue by andrewoma** [Kotlin/kotlinx.collections.immutable#5]
My library (https://github.com/andrewoma/dexx) is a largely port of Scala's collections.

It provides SortedMap/Set implementations as well as Vectors supporting 0(1) append/prepend that can be used as stack and queue implementations as well.

**Comment by paplorinc** [comment]
Related to: https://github.com/Kotlin/kotlinx.collections.immutable/issues/6

**Comment by ilya-g** [comment]
Thanks for the suggestion, but we've already settled on our own implementations, see #20
