### ISSUE TITLE
Could not resolve: org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.3

### ISSUE THREAD

**Issue by alphaho** [Kotlin/kotlinx.collections.immutable#61]
Following the README.md instructions and added below line to my gradle dependencies configuration: 

```
implementation("org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.3")
```

I got the following error message from gradle:

```
> ./gradlew build
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.3.

```

And with the following link from jcenter, I got a 404 response: https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-collections-immutable-jvm/ 

However, if I follow the links and locate the jar on the jcenter web UI, I can download the jar successfully from this page: https://bintray.com/kotlin/kotlinx/kotlinx.collections.immutable/0.3#files/org%2Fjetbrains%2Fkotlinx%2Fkotlinx-collections-immutable-jvm%2F0.3

May I know whether version 0.3 is ready to be used?

**Comment by yuriykulikov** [comment]
Add this to your build.gradle:
repositories {
        maven {
            url "https://kotlin.bintray.com/kotlinx"
        }
    }

**Comment by alphaho** [comment]
Thanks for the quick reply! With the repository configuration, it now can resolve the dependency successfully.

Maybe we need to update the README.md? As it says:

```
Add the bintray repository:

repositories {
    jcenter()
}
```

**Comment by ilya-g** [comment]
I've filed a request for bintray to investigate why not all of the artifacts are mirrored in jcenter.

**Comment by rgoldberg** [comment]
Can you publish to `mavenCentral()`, as `jcenter()` supposedly mirrors that.

I've experienced problems multiple times with `jcenter()`, but never with `mavenCentral()`, so I'd prefer to avoid using `jcenter()`.

Thanks.

**Comment by ilya-g** [comment]
Downloading from `jcenter` should be fine now.

**Comment by adam-arold** [comment]
Is there a timeline for fixing this problem? This artifact is the only transitive dependency I have which doesn't download without adding the repository explicitly. This issue is still not solved.

**Comment by ilya-g** [comment]
@adam-arold This issue was about artifacts being unavailable in jcenter. As I've checked them now once again, they are all there.

**Comment by JohannBlake** [comment]
jCenter is being permanently shut down. Where are these artifacts located now?

**Comment by ilya-g** [comment]
@JohannBlake AFAIK jcenter isn't going anywhere until Feb 2022. The current version still resides in jcenter(), and the next version will be published to maven central pretty soon. You can subscribe to #96 for updates.
