### ISSUE TITLE
A parameterless `persistentHashMapOf()`

### ISSUE THREAD

**Issue by chuckjaz** [Kotlin/kotlinx.collections.immutable#67]
FEATURE REQUEST

A parameterless version of `persistentHashMapOf()` to avoid creating a useless builder and varargs parameter when the code is just going to create its own builder anyway.

```
fun <K, V> persistentHashMapOf(): PersistentMap<K, V> = PersistentHashMap.emptyOf<K,V>()
```

Parameter-less versions of `persistentSetOf` and `persistentListOf()` already exist. It seems odd that this is missing.

**Comment by qurbonzoda** [comment]
The functions was added in 0.3.2 version of the library.
Thank you for your feedback!
