### ISSUE TITLE
What is the reasoning for this when Google Guava exists? 

### ISSUE THREAD

**Issue by thomasnield** [Kotlin/kotlinx.collections.immutable#7]
Hey I am curious, 

I am surprised Google Guava got no mention in this library's README. What is the reasoning to have this library when Google Guava exists?  Google Guava has an extensive set of collection types, including ImmutableMultiMap. Is this seeking to be a more lightweight library for just Immutable collections? Is it seeking to be more Kotlin-y?

**Comment by ilya-g** [comment]
One of the requirements for the proposed immutable collection implementations is that they should be persistent, i.e. provide an efficient way to create modified data structure sharing as most data with the original as possible.

AFAIK, Guava immutable collections are just immutable but not persistent.
