### ISSUE TITLE
Faster union/intersection implementation for sets?

### ISSUE THREAD

**Issue by belyaev-mikhail** [Kotlin/kotlinx.collections.immutable#83]
Current union (`addAll`) implementation for sets is O(logN * M) as far as I understand even when both sides have the same implementation.
It is certainly possible to improve that to log or even sub-log implementation for HAMTs by merging one-bit arrays only.
It is also possible to improve intersection, although atm you don't even have a method for intersection in the API.

Not sure if it helps maps in any way, but I guess it does.
While intersection is questionable, union is a very important and widely used operation (especially so when `+` is overloaded as union) for persistent sets and implementing this doesn't even need changing the api.

**Comment by qurbonzoda** [comment]
It would be great.

**Comment by belyaev-mikhail** [comment]
So, #86 is the first version of the pull request.
I've done some benchmarking (not the stuff I do often, so critique is welcome) and these are preliminary results:

https://docs.google.com/spreadsheets/d/1NaMgasBhqyThazU-_TVWAK2fCcnztAQ9WCRxr9lNfUw/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1lTjcPPfOZTKd4eHHrzrLOoq9SbaNf9-eEx4MCsyzfMU/edit?usp=sharing

These look promising, but there currently are a few pitfalls:

- Current implementation doesn't try its extreme to preserve persistense (namely, it does not return the same node if all the children are reference-equal to the previous node), because it's much trickier to do for `addAll`/`putAll` efficiently;
- I still struggle to design a solution for ordered maps/sets, because `addAll` cannot be implemented using `HashMap` `putAll` due to different conflict behaviour (`putAll` replaces older values, while `addAll` should retain older values, but edit the new ones);
- The whole `DeltaCounter` business may seem sloppy and less Kotlin'y than your `ModificationResult` approach, but I found massive boxing for bulk operations too heavy and it's not trivial to implement bulk operations this way (sometimes you modify against the _other_ node, not `this`);
- No `mutableAddAll`/`mutablePutAll` for now because I'm not sure if they provide any increased benefit (and, tbh, I still don't fully get how to get around your `MutabilityOwnership` correctly);
- No intersection yet, because that would involve changing the current interfaces.

Feel free to check out and destroy the PR =)

**Comment by belyaev-mikhail** [comment]
Some comments on the benchmarks: I tested two scenarios, _typical_ and _worst-case_ where typical is uniting two non-intersecting sets/maps and worst case is two completely identical, but different, sets.
The choice is due to this approach should not perform well in the second variant (theoretically, it should be the same O(N * logM) as the old mutable approach), which is somewhat true in practice.
No enormous speedup, but it seems decent to me.

I didn't try to construct a benchmark for _best-case_ scenario, (say, two sets with all hashes being different in their first bits)  because it has constant complexity, but seems very unrealistic to me.

**Comment by ilya-g** [comment]
> Current implementation doesn't try its extreme to preserve persistense (namely, it does not return the same node if all the children are reference-equal to the previous node), because it's much trickier to do for addAll/putAll efficiently;

This would be unfortunate, because there are use cases when a reference equality check is used after an operation to find out whether it has actually changed content (instead of boolean flag that is returned from mutable collection operations).

**Comment by belyaev-mikhail** [comment]
Well, it can be done either by checking array element reference-equality manually after the actual logic, or by doing it on-the-fly using two additional masks. Either way we throw away the array we allocated, but there's no way avoiding it, I guess.
I'll look into it.

**Comment by belyaev-mikhail** [comment]
Ok, so I implemented the array element checking, did some benchmarks and it does not seem to introduce much overhead (or any at all, for that matter).

**Comment by qurbonzoda** [comment]
The asked optimisation was implemented by @belyaev-mikhail and merged to `master` (690343ace1aa4a47463f2ce42ae319876014ee47).

**Comment by belyaev-mikhail** [comment]
Well, not really) I am still investigating the intersection and other bulk ops and will  make it a separate PR, so this is not the end)

**Comment by belyaev-mikhail** [comment]
But maybe opening a separate issue for that will make more sense, too
