### ISSUE TITLE
Mutable Collections should not Inherit from Immutable Collections

### ISSUE THREAD

**Issue by hellerim** [Kotlin/kotlinx.collections.immutable#87]
The concepts of being immutable and being mutable are mutually exclusive. The name of an immutable collection interface already states a contract. Extending an immutable interface by adding mutability methods breaks this contract. In addition, Barbara Liskov's substitution principle is broken: You cannot replace the base class with a derived class in all situations without damaging the expected behavior.

However, Kotlin has all it needs to clearly separate such interfaces and make them mutually incompatible:

`
class ImmutabilityContractViolationException : Exception()

interface IImmutable {
    fun read(): Int
    fun write(value: Int): Nothing  = throw ImmutabilityContractViolationException()
}

interface IMutable {
    fun read(): Int
    fun write(value: Int) : Unit
}
`

**Comment by hellerim** [comment]
In addition, all immutable interfaces could inherit from a single immutability marker interface. So, instead of having mutable and immutable iterators, we could check for immutability explicitly, e.g. whenever we need to consider concurrency.

**Comment by ilya-g** [comment]
Could you point specifically where a mutable collection is inherited from an immutable one?

**Comment by hellerim** [comment]
In _Kotlin in Action_ (by Dmitry Jemerov and Svetlana Isakova, Manning, 2017), in section 6.3.2, the following is stated: "To modify the data in the collection, use the `kotlin.collections.MutableCollection interface`. It extends the regular `kotlin.collections.Collection` and provides methods for adding and removing the elements, clearing the collection, and so on." The rest of this section and section 6.3.3 go into more detail.

**Comment by hellerim** [comment]
I forgot to mention that in the beginning of setion 6.3.2, they state that the _kotlin.collections.collection_ "interface doesn't have any methods for adding or removing elements.".

**Comment by JakeWharton** [comment]
`Collection` is a read-only interface along with `MutableCollection` which are in the Kotlin standard library, separate from the `ImmutableCollection` interface which is in this library.

**Comment by hellerim** [comment]
Probably, the point is that we should have another collection interface with the same methods as `kotlin.collections.collection`, but which does not care about immutability, so that both `kotlin.collections.collection` and `kotlin.collections,MutableCollection` could inherit from it. Adding throwing versions of the mutating methods of the `kotlin.collections.MutableCollection` interface to the `kotlin.kollections.Collection` interface makes sure that no class or interface may implement both - they are mutually exclusive. Making `kotlin.kollections.Collection` inherit from the marker interface mentioned above still makes sense. As a result, while the new proposed interface is ignorant about the immutability contract, the other to then clearly indicate that they conform to this contract or break it, respectively.

**Comment by hellerim** [comment]
@JakeWharton: Looking at the docs [MutableCollection](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-collection/), it appears to me that both interfaces are not completely separate, since one extends the other.

**Comment by hellerim** [comment]
It appears that the term "read-only" is somewhat confusing. For instance, if I declare a class member as _readonly_ in C#, the meaning is that it cannot be changed after initialization. It is not the same as a contant since its value can be different for every class instance. Here, apparently read-only refers to the lack of mutating methods. If this is meant, then my first critics is not justified. But it still makes sense to talk about immutability which prohibits mutating methods. Instead of adding a new base interface one should add an interface `ImmutableCollection` which indicates that it respects an immutaability contract.

**Comment by hellerim** [comment]
idea: 
`interface Immutable { } // marker interface
interface ImmutableCollection<T> extends Immutable, kotlin.collections.Collection<T> {
    fun add(element: T): Nothing = throw ImmutabilityContractViolationException()
    ...
}`
