### ISSUE TITLE
Alternative API

### ISSUE THREAD

**Issue by amaranth** [Kotlin/kotlinx.collections.immutable#9]
After reading the other discussions about API design and backing implementation I decided to put some more work in to the tinkering I've been doing on persistent data structures. I think I now have enough done to start a discussion about the best approach.

https://github.com/amaranth/persistent-collections

There are interfaces for immutable collections, lists, sets, maps, sorted sets, and sorted maps. The implementation for lists is a bit-partitioned vector trie with O(log<sub>32</sub>n) scaling. The hash map is sort of halfway between the standard clojure style HAMT and the CHAMP design, I use separate arrays for child nodes and data. The tree map is using an AA tree, which apparently Scala uses as well. The hash set and tree set are just wrappers around the map implementations. There is also a (most likely broken) finger tree implementation which I plan to try to use for a priority queue and possibly ordered sets and maps.

The performance of the library is... okay. I'm sure more optimization work can be done but my main goal was to get something that works first. On that note the unit tests could certainly use some work, right now they're mostly just ported from @andrewoma's dexx library (and I've just noticed the license gradle plugin wiped his name from the copyright headers, oops) but they at least show things aren't completely broken.

I'd love to see an API like this adopted, even if we decide to use UncleJim or dexx or pcollections for the backing implementation. The key design aspect mirrors the approach UncleJim uses in that the way to do mass updates to one of the collections in a performant way is to transform a `Sequence` and then turn that in to a new collection. This lets us avoid exposing the transient versions to the API which should remove any chance to misuse them and accidentally lose immutability.

**Comment by ilya-g** [comment]
I appreciate your effort in tailoring clojure collection implementations into the kotlin-friendly interfaces.
Currently we're interested in the ordered map/set implementations to the most. If we had them, we could publish the prototypes.

> The key design aspect mirrors the approach UncleJim uses in that the way to do mass updates to one of the collections in a performant way is to transform a `Sequence` and then turn that in to a new collection.

Does it make the collection to be not persistent anymore? As after a modification it does not share the storage with the original collection no matter how massive the modification was.

**Comment by amaranth** [comment]
For basic bulk operations (`addAll`, `removeAll`, `retainAll`) we can use transients internally to do it efficiently but for more specialized operations you'd either have to take the hit of doing the path copying for each operation or use `Sequence` to efficiently create an entirely new collection. If we require the collections to implement `take` and `drop` as well you can use the methods that work with transients internally to build a wide variety of operations with minimal overhead.

**Comment by ilya-g** [comment]
> you'd either have to take the hit of doing the path copying for each operation or use Sequence to efficiently create an entirely new collection.

These are two options, but they are not the only two options available. Current prototype shows that we can neither copy the entire collection on modification, nor resort to using Sequence.

**Comment by amaranth** [comment]
Sure you can avoid it if you expose the transient but the whole point of optimizing `Sequence` operations was to avoid doing that. A few months ago I also tried to write this using `Mutable*` for the transients like your current design does but abandoned that work. I feel like exposing a mutable version in the API is basically giving up on the idea of having immutable collections.

**Comment by IamSungod** [comment]
I really expect lazy streams API add these powerful and convenient methods :
repeat/cycle, repeatedly/generate, iterate, unfold, resource, reject,
like in Elixir and Clojure: https://hexdocs.pm/elixir/Stream.html#unfold/2

**Comment by ilya-g** [comment]
@IamSungod you should take a look at [Sequence](http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/-sequence/index.html) interface and extension functions in [kotlin.sequences](http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/index.html) package.

If some operation is missing you could easily implement it with the [buildSequence](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines.experimental/build-sequence.html) function, for example `repeat` is just:
```
fun <T> Sequence<T>.repeat() = buildSequence {
    while (true) yieldAll(this@repeat)
}
```

**Comment by IamSungod** [comment]
@ilya-g Thanks, if provided by stdlib will be more convenient to every average programmer.
I think, **one of the programming trend is the Lazy Sequences** .
Is there the equivalence like Transducers in Clojure ? https://github.com/matthiasn/talk-transcripts/tree/master/Hickey_Rich

**Comment by qurbonzoda** [comment]
Closing this issue as obsolete. 
Already for a long time, the implementations in this library have used state-of-the-art data structures.
Bulk updates now use a builder (a.k.a. transient) to reduce allocation and improve performance.
