### ISSUE TITLE
Published POMs are missing license info

### ISSUE THREAD

**Issue by li-wjohnson** [Kotlin/kotlinx.collections.immutable#98]
For example:
https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-collections-immutable-jvm/0.3.3/kotlinx-collections-immutable-jvm-0.3.3.pom

Compare with:
https://bintray.com/kotlin/kotlinx/download_file?file_path=org%2Fjetbrains%2Fkotlinx%2Fkotlinx-coroutines-core%2F1.4.2%2Fkotlinx-coroutines-core-1.4.2.pom

This is causing issues with our license compliance checks.

**Comment by qurbonzoda** [comment]
In the latest release, `0.3.4`, the license information is included.
Please update to the latest version and check if the problem remains.
Thank you for your feedback!
