### ISSUE TITLE
How to address jcenter() removal in Android Studio Arctic Fox Canary 8

### ISSUE THREAD

**Issue by ezrover** [Kotlin/kotlinx.collections.immutable#99]
This library depends on on Jcenter but the new studio is asking for its removal:

Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.

how can this issue be alleviated?

**Comment by qurbonzoda** [comment]
We are working on the issue. Please follow the issue: https://github.com/Kotlin/kotlinx.collections.immutable/issues/96
